/*
 * Copyright 2026 Kazimierz Pogoda / Xemantic
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.xemantic.nano.plentyofroom.structure

import com.xemantic.kotlin.test.assert
import java.io.File
import kotlin.test.Test

/**
 * `T-272`'s `P2`: a study declares a **typed input handle**, it does not spell a path.
 *
 * The registry is generated by `tools/T-272-emit-result-inputs.py` from the files git tracks in
 * `gpd/results/`, and the generator is also a `--check`. What is asserted here is what a
 * generator cannot: that every handle resolves to a file that is *there*, that the directory is
 * spelled exactly once, and that a handle's `tag` is the one
 * `tools/reemission-order.py` sorts on.
 */
class ResultInputsTest {

    private val directory = File(RESULT_DIRECTORY)

    // --- gate 1: every handle names a file that exists ------------------------------------------

    @Test
    fun `every handle resolves to a committed result file`() {
        val missing = ResultInputs.all.filterNot { it.file().isFile }
        assert(missing.isEmpty()) { "handles with no file: ${missing.map { it.fileName }}" }
    }

    @Test
    fun `the registry is not empty and every handle is distinct`() {
        assert(ResultInputs.all.size > 100)
        assert(ResultInputs.all.map { it.fileName }.toSet().size == ResultInputs.all.size)
    }

    // --- gate 2: the two ways of naming a file agree --------------------------------------------

    @Test
    fun `a handle's path is the directory and its own name`() {
        ResultInputs.all.forEach {
            assert(it.path == "$RESULT_DIRECTORY/${it.fileName}")
            assert(it.file().path == it.path)
        }
    }

    /**
     * The shape `CH-0092`'s twenty invisible edges were assembled in: a directory in the caller
     * and a name in a helper. With a handle the name is no longer in the helper, and the two
     * spellings must land on the same file.
     */
    @Test
    fun `the directory-joined form names the same file as the direct one`() {
        ResultInputs.all.forEach {
            assert(it.file(directory).path == it.file().path)
        }
    }

    // --- gate 3: the tag is the handle the topological sort uses --------------------------------

    @Test
    fun `every handle's tag is the first two dash-separated fields of its file name`() {
        ResultInputs.all.forEach {
            val expected = it.fileName.split("-").take(2).joinToString("-")
            assert(it.tag == expected)
        }
    }

    /**
     * `T-119` writes two committed result files — a EuropePMC survey from `tools/` and a Kotlin
     * study — so a task id does **not** identify a file. `ofTag` returns `null` there rather than
     * picking one, and the collision is a finding about `tools/reemission-order.py`, whose whole
     * topological sort is keyed on exactly this identifier.
     */
    @Test
    fun `a task id that names two files resolves to neither`() {
        val ambiguous = ResultInputs.all.groupBy { it.tag }.filterValues { it.size > 1 }
        assert(ambiguous.keys == setOf("T-119")) { "ambiguous tags: ${ambiguous.keys}" }
        assert(ResultInputs.ofTag("T-119") == null)
        assert(ResultInputs.ofTag("T-3b")!!.fileName == "T-3b-tile-edge-load-profile.json")
        assert(ResultInputs.ofTag("T-999") == null)
    }

    // --- gate 4: every path a source still spells is a file the registry knows -----------------

    /**
     * A study's own **output** keeps its literal, deliberately: `tools/check-entry-points.py`
     * finds a study's result file by following the binding to its `.writeText`, and that reading
     * must keep working. So what Kotlin can assert here is the weaker, sound thing — every
     * `gpd/results/…` path still spelled in a main source names a file the registry knows.
     *
     * The strong statement — *no source READS a result file by path* — needs the read/write
     * distinction, which is a static analysis of the binding and already exists once, in
     * `tools/result-reader-census.py`. Re-implementing it here would be a second implementation
     * of the rule that decides the whole census, and `CLAUDE.md` records what two implementations
     * of one rule do. It is gated in `tools/T-272-header-census.py --reads` instead.
     */
    @Test
    fun `every result path still spelled in a main source has a handle`() {
        val known = ResultInputs.all.map { it.fileName }.toSet()
        val pattern = Regex("""File\(\s*"$RESULT_DIRECTORY/([A-Za-z0-9._-]+\.json)"\s*\)""")
        val orphans = File("src/main/kotlin").walkTopDown()
            .filter { it.extension == "kt" }
            .flatMap { pattern.findAll(it.readText()).map { match -> match.groupValues[1] } }
            .filterNot { it in known }
            .toSet()
        assert(orphans.isEmpty()) { "paths with no handle: $orphans" }
    }
}
